apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: echo-server
  name: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo-server
    spec:
      containers:
      - image: sglahn/echo-server:latest
        name: echo-server
        resources: {}
        livenessProbe:
          httpGet:
            path: /admin/live
            port: 8080
        readinessProbe:
          httpGet:
            path: /admin/ready
            port: 8080
status: {}
