name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract Git Commit Hash
      id: vars
      run: echo "GIT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      run: |
        TIMESTAMP=$(date +'%Y%m%d%H%M%S')
        IMAGE_TAG="$TIMESTAMP-${{ env.GIT_COMMIT }}"
        docker build -t sglahn/echo-server:$IMAGE_TAG .
        docker push sglahn/echo-server:$IMAGE_TAG

    - name: Update Kubernetes Manifests
      run: |
        sed -i "s|PLACEHOLDER_TAG|$IMAGE_TAG|g" /Users/sglahn/Personal/echo-server/deployments/base/kustomization.yaml
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add /Users/sglahn/Personal/echo-server/deployments/base/kustomization.yaml
        git commit -m "Update image tag to $IMAGE_TAG"
        git push

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -k /Users/sglahn/Personal/echo-server/deployments/dev
